### ISSUE TITLE
ubuntu下编译报错

### ISSUE THREAD

**Issue by zhaoyangxia1990** [zlgopen/awtk-mvvm-c-examples#1]
Ubuntu编译报错，提示：src/table_csv_view_slidable.c:29:10: fatal error: confirmable_button_register.h: No such file or directory
   29 | #include "confirmable_button_register.h"

整个目录查找没有confirmable_button_register.h文件，也没有那个文件定义confirmable_button_register()函数

**Comment by xianjimli** [comment]
不好意思，文档没更新，你还要取一下awtk-widget-slidable-row。谢谢

6.获取 awtk-widget-slidable-row 并编译
```
git clone https://github.com/zlgopen/awtk-widget-slidable-row.git
cd awtk-widget-slidable-row; scons; cd -
```
